### ISSUE TITLE
Meditation Tab Updating

### ISSUE THREAD

**Issue by ryank85** [Sirimangalo/meditation-plus-server#11]
The meditation tab doesn't update in real-time, have to refresh the entire page. Not sure if intended

**Comment by ryank85** [comment]
It seems to be updating now, before it wasn't. I'll keep an eye on it to see what circumstances might reproduce this.

**Comment by binarious** [comment]
It should be. The tab receives push updates from the server whenever something changes. Besides that the whole tab will be refreshed every minute. Please open another issue in the client repository when you were able to reproduce this. https://github.com/Sirimangalo/meditation-plus-angular
