### ISSUE TITLE
Menu text shown briefly

### ISSUE THREAD

**Issue by yuttadhammo** [Sirimangalo/meditation-plus-server#6]
On loading the site, it shows the text "Menu" briefly before"Meditation+" Not a significant issue, but probably an easy fix?

**Comment by binarious** [comment]
With loading site you mean the initial loading screen where only "Loading..." is shown? I can't see the sidenav there. What do I need to do to reproduce the error?

**Comment by yuttadhammo** [comment]
No, after the loading text, once the app is shown, at the top there is the text "Menu" briefly before being overlapped and then replaced by "Meditation+"

**Comment by yuttadhammo** [comment]
It only seems to happen on first load in the browser. Refreshing doesn't show it, but if i take Firefox out of Android memory and restart it, it will happen the first time

**Comment by binarious** [comment]
I see. The problem here is that `<md-icon>menu</md-icon>` is visible as plain text until the Icon font is loaded. Can't think of an easy fix for that. When following the recommended way of installing the app (adding it to the homescreen) the problem goes away.
