### ISSUE TITLE
Admin should be able to remove existing appointments

### ISSUE THREAD

**Issue by yuttadhammo** [Sirimangalo/meditation-plus-server#8]
I should be able to remove anyone's appointment, maybe simply by clicking on it.

**Comment by binarious** [comment]
Right. You can just save the appointment without changing anything in the admin section as a workaround. That should remove the registered user, too.

**Comment by binarious** [comment]
Moved issue to the client repository https://github.com/Sirimangalo/meditation-plus-angular/issues/64
